spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/leaderboard
    username: postgres
    password: fakhr
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true